config/routes.rb
Treebook::Application.routes.draw do
  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  rescue_from ActiveModel::MassAssignmentSecurity::Error, with: :render_permission_error

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order('created_at desc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = current_user.statuses.new
    @status.build_document

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = current_user.statuses.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        current_user.create_activity(@status, 'created')
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    @document = @status.document

    @status.transaction do
      @status.update_attributes(params[:status])
      @document.update_attributes(params[:status][:document]) if @document
      current_user.create_activity(@status, 'updated')
      unless @status.valid? || (@status.valid? && @document && !@document.valid?)
        raise ActiveRecord::Rollback
      end
    end
    
    respond_to do |format|
      format.html { redirect_to @status, notice: 'Status was successfully updated.' }
      format.json { head :no_content }
    end
  rescue ActiveRecord::Rollback
    respond_to do |format|
      format.html do
        flash.now[:error] = "Update failed."
        render action: "edit"
      end
      format.json { render json: @status.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = current_user.statuses.find(params[:id])
    @status.destroy
    current_user.create_activity(@status, 'deleted')

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal", multipart: true}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :content, input_html: { rows: 4, class: 'input-xxlarge' } %>
  <%= f.fields_for :document do |document_fields| %>
    <% if document_fields.object.attachment? %>
    <div class="control-group">
      <label class="control-label">Current attachment</label>
      <div class="controls">
        <%= link_to document_fields.object.attachment_file_name, document_fields.object.attachment.url %>
      </div>
    </div>
    <%= document_fields.input :remove_attachment, as: :boolean, label: "Remove attachment?" %>
    <% end %>
    <%= document_fields.input :attachment, as: :file %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to "Back", statuses_path, class: 'btn' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<%= page_header do %>
  <h1>Edit Status</h1>
<% end %>

<%= render 'form' %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All of the Statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
  <% if can_display_status?(status) %>
    <div class="status media">
      <%= avatar_profile_link status.user, {}, class: 'pull-left' %>
      <div class="media-body">
        <h4 class="media-heading"><%= status.user.full_name %></h4>
        <p><%= status.content %></p>
        <%= status_document_link(status) %>
        <div class="meta">
            <%= link_to time_ago_in_words(status.created_at) + " ago", status %> 
            <% if signed_in? && current_user == status.user %>
            <span class="admin">
              | <%= link_to "Edit", edit_status_path(status) %> | 
              <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
            </span>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/statuses/new.html.erb
<%= page_header do %>
  <h1>New Status Update</h1>
<% end %>

<%= render 'form' %>

app/views/statuses/show.html.erb
<div class="row">
  <div class="span8 offset2">
    <%= page_header do %>
      <h1>
        <%= avatar_profile_link @status.user %>
        <%= @status.user.full_name %>
        <small><%= time_ago_in_words(@status.created_at) + " ago" %></small>
      </h1>
    <% end %>

    <p>
      <%= @status.content %>
    </p>

    <hr />

    <% if @status.document && @status.document.attachment? %>
      <%= status_document_link @status %>
      <hr />
    <% end %>

    <div class="meta">
      <%= link_to 'Back', statuses_path %>
      <% if signed_in? && @status.user == current_user %>
        |
        <%= link_to "Edit", edit_status_path(@status) %> | 
        <%= link_to "Delete", @status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
      <% end %>
    </div>
  </div>
</div>