config/routes.rb
Treebook::Application.routes.draw do
  resources :activities, only: [:index]

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  scope ":profile_name" do
    resources :albums do
      resources :pictures
    end
  end

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EMG Network</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<% if user_signed_in? %>
				<%= link_to "EMG Network", activities_path, class: 'brand' %>
				<% else %>
				<%= link_to "EMG Network", root_path, class: 'brand' %>
				<% end %>
				<ul class="nav">
					<li><%= link_to "All Statuses", feed_path %></li>
					<% if user_signed_in? %>
						<li><%= link_to "Activity Feed", activities_path %></li>
					<% end %>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to 'Albums', albums_path(current_user) %></li>
						<li><%= link_to 'Friends', user_friendships_path %></li>
						<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
						<li><%= link_to "Log Out", logout_path %></li>
					<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>

				</ul>
			</div>
		</div>
	</div>
	<div class="container">
		<%= render_breadcrumbs %>
		
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>
		    
		<%= yield %>
	</div>
</body>
</html>